Diplom part 3 (1-ая итерация)
LipatovKir/java-explore-with-me pull request #7
Opened 2023-09-12 20:06 UTC by LipatovKir

2023-09-13 08:54 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к работе.

2023-09-13 08:54 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/checkservice/CheckServiceImpl.java
> +        return entity.orElseThrow(() -> new NotFoundException(entityClass, entityId + " NOT FOUND! "));
так у вас везде сообщение об ошибке на русском, а тут зачем меняете?

2023-09-13 08:54 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comments/controller/CommentAdminController.java
> +                                            @Positive
Вы проверяли? У вас без Validated над классом будет работать?)

2023-09-13 08:54 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comments/controller/CommentPrivateController.java
> +                                                     @Positive
аналогично

2023-09-13 08:54 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comments/model/Comment.java
> +        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
Слишком длинная строка

2023-09-13 08:54 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comments/model/Comment.java
> +        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
Слишком длинная строка

2023-09-13 08:54 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentServiceImpl.java
> +@Slf4j
Не вижу логгирования в классе

2023-09-13 08:54 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentServiceImpl.java
> +        if (newMessage != null && !newMessage.isBlank()) {
Можно заменить на stringUtils

2023-09-13 08:54 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentServiceImpl.java
> +    public List<CommentShortDto> getCommentsByUserId(String rangeStart, String rangeEnd, Long userId, Integer from, Integer size) {
Логичнее тогда обьект Page возвращать

2023-09-13 08:54 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentServiceImpl.java
> +    public void validateDateTime(LocalDateTime startTime, LocalDateTime endTime) {
Он точно должен быть публичным?

2023-09-13 18:52 UTC, LipatovKir commented on ewm-service/src/main/java/ru/practicum/comments/controller/CommentAdminController.java
> +                                            @Positive
Да, проверял, работает. аннотацию добавил.

2023-09-13 18:52 UTC, LipatovKir commented on ewm-service/src/main/java/ru/practicum/comments/controller/CommentPrivateController.java
> +                                                     @Positive
исправил

2023-09-13 19:13 UTC, LipatovKir commented on ewm-service/src/main/java/ru/practicum/comments/model/Comment.java
> +        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
исправил

2023-09-13 19:14 UTC, LipatovKir commented on ewm-service/src/main/java/ru/practicum/comments/model/Comment.java
> +        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
исправил

2023-09-13 19:19 UTC, LipatovKir commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentServiceImpl.java
> +        if (newMessage != null && !newMessage.isBlank()) {
исправил

2023-09-13 19:21 UTC, LipatovKir commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentServiceImpl.java
> +    public void validateDateTime(LocalDateTime startTime, LocalDateTime endTime) {
он только в этом классе используется, исправил на private

2023-09-13 19:35 UTC, LipatovKir commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentServiceImpl.java
> +@Slf4j
исправил

2023-09-13 19:40 UTC, LipatovKir commented on ewm-service/src/main/java/ru/practicum/checkservice/CheckServiceImpl.java
> +        return entity.orElseThrow(() -> new NotFoundException(entityClass, entityId + " NOT FOUND! "));
Добрый день! хотел унифицировать под разные рода сущностей. Исправил, перефразировал.

2023-09-13 19:55 UTC, LipatovKir commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentServiceImpl.java
> +    public List<CommentShortDto> getCommentsByUserId(String rangeStart, String rangeEnd, Long userId, Integer from, Integer size) {
исправил

2023-09-14 06:14 UTC, Frilock approved these changes
Здорово, принято

2023-09-14 06:28 UTC, merged